# Generated by Django 3.0.1 on 2020-02-07 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=60)),
                ('companyAddress', models.CharField(max_length=60)),
                ('companyContactNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=60)),
                ('jobType', models.CharField(max_length=20)),
                ('postedDate', models.DateField()),
                ('deadline', models.DateField()),
                ('jobPost', models.FileField(upload_to='')),
                ('jobProvider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Company')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobSeekerName', models.CharField(max_length=60)),
                ('jobSeekerAddress', models.CharField(max_length=60)),
                ('jobSeekerContactNo', models.IntegerField()),
                ('applyJob', models.ManyToManyField(related_name='applyJob', to='user.JobPost')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('comments', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
